import NumberCard from './numberCard'
import Quote from './quote'
import Sales from './sales'
import Weather from './weather'
import RecentSales from './recentSales'
import Comments from './comments'
import Completed from './completed'
import Browser from './browser'
import Cpu from './cpu'
import User from './user'
import DynamicChartComponent from './DynamicChartComponent'
import ElecTimerChart from './ElecTimerChart'
import FactoryMap from './factoryMap'
export { NumberCard, Quote, Sales, Weather, RecentSales, Comments, Completed, Browser, Cpu, User,DynamicChartComponent,ElecTimerChart,FactoryMap }
